# Generated by Django 5.0.6 on 2024-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_logincredentials_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='Category',
            field=models.CharField(default='Fish', max_length=100),
        ),
    ]
